# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BearingDistance
                                 A QGIS plugin
 This plugin returns the bearing and distance of the sides of polygons.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-07
        copyright            : (C) 2022 by Yahaya Isah Makarfi
        email                : yahaya.makarfi@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yahaya Isah Makarfi'
__date__ = '2022-04-07'
__copyright__ = '(C) 2022 by Yahaya Isah Makarfi'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BearingDistance class from file BearingDistance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bearing_distance import BearingDistancePlugin
    return BearingDistancePlugin()
    
    from .bearing_distance import BearingDistance2Plugin
    return BearingDistance2Plugin()
    
    from .bearing_distance import BearingDistance3Plugin
    return BearingDistance3Plugin()
    
    from .bearing_distance import BearingDistance4Plugin
    return BearingDistance4Plugin()
    
    from .bearing_distance import BearingDistance5Plugin
    return BearingDistance5Plugin()
    
